### PR TITLE
Fix multiline expectations

### LINKED ISSUE #33: Editor style eval to multiline comment fails at test generation time
## Source
From [slack](https://clojurians.slack.com/archives/C02NSHB3T0A/p1747055717943509).

## Issue
Clojure support in editors allows for evaluating to a comment.

When the evaluation result is long, the comment can wrap:

```clojure
(repeat 7 "hey there")
;; => ("hey there"
;;     "hey there"
;;     "hey there"
;;     "hey there"
;;     "hey there"
;;     "hey there"
;;     "hey there")
```

Currently, test-doc-blocks will barf on this at test generation time with an Unexpected EOF exception.

## Diagnosis
These syntaxes work:

````md
# README

```clojure
;; this works
(map inc [1 2 3 4 5 6])
=> [2 3 
    4 5 
    6 7]
```

```clojure
;; this works...
(map inc [1 2 3 4 5 6])
;; => [2 3 
       4 5 
       6 7]
```
````
This one does not:
````
```clojure
;; this fails at test generation time with Unexpected EOF
(map inc [1 2 3 4 5 6])
;; => [2 3 
;;     4 5 
;;     6 7]
```
````

## Option 1: Do nothing
It seems reasonable that a multiline eval to comment should work. 
So, doing nothing seems user-cruel.

## Option 2: Support 
Test-doc-blocks does support multiline stdout, I don't remember if I had a rationale for not supporting eval to multiline comment. Maybe just a blind spot?

Stdout multiline continuation requires that subsequent lines start with a single `;`.
This allows test-doc-blocks to distinguish output from assertion tokens.

Is there any similar concern for eval to comment?

## Proposal
Barring any real technical reason not to, I think we should support option 2.

Also, docs should be updated to show multiline examples.

### PR DESCRIPTION
**Pull request by mattiuusitalo**
Fixes #33 

Allows both old style and new style
```Clojure
   ;; Expected output can span multiple lines
   (assoc {} :foo :bar :quu :baz)
   ;; => {:foo :bar
   ;      :quu :baz}

   ;; One can use multiple leading semicolons as well
   (assoc {} :foo :bar :quu :baz)
   ;; => {:foo :bar
   ;;     :quu :baz}

   ;; Or if you prefer, without the leading comment character
   (assoc {} :foo :bar :quu :baz)
   ;; => {:foo :bar
          :quu :baz}
```

Looking at the example above one can see the value of leading comments, as the examples written like that are rendered more nicely.

### CODE REVIEW

**Comment by lread** [comment]
Thanks @mattiuusitalo! I am taking a peek at your change on my dev box.

If I understand it correctly, we can still distinguish stdout from eval when stdout contains the `=>` syntax.

For example:
````
```clojure
(do (println "When do I end?\n=> 77")
    42)
;; =stdout=> When do I end?
; => 77
;; => 42
```
````

But, we don't force the single semicolon line continuation on the user if there is no ambiguity from the stdout output:

````
```clojure
(do (println "When do I end?\n= 77")
    42)
;; =stdout=> When do I end?
;; = 77
;; => 42
```
````

If this is what you intended, I like it. 
The single semicolon continuation is awkward to read, and it is probably relatively rare that stdout/stderr output will start with `=>`, and when it does, we have a way for the user to handle it.

Same idea for ambiguous evals, right?

In the oddball case where needed to, we would not do this:

````
```clojure
[:when :do :i '=stdout=> (inc 41) :end?]
;; => [:when 
;; :do 
;; :i 
;; =stdout=> 42 
;; :end?]
```
````

But instead this:
````
```clojure
[:when :do :i '=stdout=> (inc 41) :end?]
;; => [:when 
; :do 
; :i 
; =stdout=> 42 
; :end?]
```
````

Have I understood your thinking?

**Comment by mattiuusitalo** [comment]
First of all, rebased the branch with the latest changes from main, so heads up if you try to pull from the same branch.

> Have I understood your thinking?

I didn't anticipate the case where =stdout=> or =clj=> would be part of the expected output. I'm happy that the single semicolon case makes it work though. That would retain the backwards compatibility with earlier versions, right?

I noticed that this is a very specific case with just the symbols =stdout=> =stderr=> =clj=> etc being printed. For users of this library that wouldn't be a problem since they could just use different symbols, I think.

Making a mini DSL like this that still retains the human readable aspect of the code blocks, which is after all their original intention, is surprisingly challenging I must say.

**Review by lread — COMMENTED** [review]
I think this looks good!

Supporting multiline commented eval values adds complexity. 
Because of this, I think I'd add more tests like the `larger-test`. 
If you've had enough, I could take a shot at it.

I'd also expand on the docs a bit and explain more options for multiline. I can also take a stab at this.

**Comment by lread** [comment]
@mattiuusitalo, just an FYI, I'll go ahead and collaborate by making commits to this PR.

**Comment by lread** [comment]
Test-doc-blocks has the luxury of having only a handful of fans/users.

I've tried this PR against known users of test-doc-blocks:
- etaoin
- rewrite-clj
- honeysql
- oksa (new to me, thanks grep.app!)

I found breakages for etaoin and honey-sql. They are all of the same flavour. This is good, we only found one problem, and it is easy to understand.

An example code block from etaoin:

```adoc
[source,clojure]
----
;; switch to the first top-level iframe with the main page: frame1
(e/switch-frame-first driver)
;; downward to the first iframe with frame1: frame2
(e/switch-frame-first driver)
(e/get-element-text driver :in-frame2)
;; => "In frame2 paragraph"
;; back up to frame1
(e/switch-frame-parent driver)
;; back up to main page
(e/switch-frame-parent driver)
----
```

The `;; back up to frame1` comment is now interpreted as part of the expected value and causes a failure.

Because an evaluation results in a form, and we already depend on rewrite-clj which parses forms, we can probably more intelligently figure out what our test expectation should be here and not include any unwanted comments.

I'll explore this idea.

**Comment by lread** [comment]
Ok, seems to pass on all known projects now (test-doc-blocks, honeysql, rewrite-clj, oksa).

I've got one or two more things I'd like to check before merging.

If you have any feedback on my changes, I am happy to hear it!

File: test/lread/test_doc_blocks/impl/body_prep_test.clj [hunk 1]
```diff
@@ -103,87 +104,169 @@
   (testing "missing ;; is ok for assertion"
     (is (= "=stdout=> [\"hello there\"]\n"
            (sut/prep-block-for-conversion-to-test "=stdout=> hello there"))))
-  (testing "no conversion when not ;;"
+  (testing "no conversion when assertion token line does not startw with ;;"
```
Comment (mattiuusitalo) [inline test/lread/test_doc_blocks/impl/body_prep_test.clj:107]: Small typo "startw"

**Review by mattiuusitalo — COMMENTED** [review]
Nice! Everything works in the tests I get from malli readme's too

File: test/lread/test_doc_blocks/impl/body_prep_test.clj (hunk 1 above)
Comment (lread) [reply test/lread/test_doc_blocks/impl/body_prep_test.clj:107]: Ah! Thanks! I am... the king of typos!

**Comment by lread** [comment]
@mattiuusitalo I did one more verification. 
```
for each of [etaoin rewrite-clj honeysql oksa]
  generate test-doc-blocks tests with this PR
  generate test-doc-blocks tests with without this PR
  diff
```
Looks good! The only change I see in the diff is your fix from #29.

Shall I merge to main and cut a release?

**Comment by mattiuusitalo** [comment]
I think we are good to go! My use cases work as well. Nice addition with that regression test.
